# Parámetros Globales
default-lease-time 86400;      # 1 día en segundos
max-lease-time 691200;         # 8 días en segundos
option domain-name "christian.test";
option domain-name-servers 10.0.0.2, 4.4.4.4;

authoritative;

# Subred de la red interna intnet
subnet 192.168.57.0 netmask 255.255.255.0 {
  range 192.168.57.20 192.168.57.50;
  option routers 192.168.57.10;
  option broadcast-address 192.168.57.255;
}

# Reserva estática para la impresora basada en la MAC
host printer {
  hardware ethernet 08:00:27:11:22:33;
  fixed-address 192.168.57.100;
  default-lease-time 7200;     # 2 horas en segundos
}